### ISSUE TITLE
scAllele run mode training error

### ISSUE THREAD

**Issue by maling-tech** [gxiaolab/scAllele#12]
hello,

When I was running the example code in the repository, the program threw an error. Based on the error message in the console, I found the location in the code where the error occurred, as shown in the image. Can you tell me what the initial value of the ALL_VARS_LIST variable is?

![190baf77207a13005985330fbf65d91](https://github.com/gxiaolab/scAllele/assets/18088379/e07d4645-dff3-4dea-8a91-925edb10c87d)

![image](https://github.com/gxiaolab/scAllele/assets/18088379/a9bbe145-ff47-4491-a03f-f686adb72328)

![image](https://github.com/gxiaolab/scAllele/assets/18088379/5ff4665e-4ba6-4647-8cd3-6e3731058aea)

**Comment by giovanniquinones** [comment]
Thanks for bringing this up. 
This is a bug in the code and will make sure the update the scripts to address this. 
May I ask, why are you training a new model?

**Comment by giovanniquinones** [comment]
The github code and Pypi have been updated. Please try again

**Comment by maling-tech** [comment]
Thank you. The problem has been fixed!
