### ISSUE TITLE
Benchmarking on Science Advances publication and 10X data

### ISSUE THREAD

**Issue by BiotechPedro** [gxiaolab/scAllele#7]
Hi Giovanni, 

First of all, congrats for the cool tool you developed! I specially like that the read-specific variant calling enables allele-specific splicing analyses.

(i) I was wondering why did you do the benchmark against freebayes and not **cellsnp-lite**, since the latest also works for SMART-seq2 data (modes 1b and 2b). Also, (ii) are you planning to show how it works with **droplet-based data** in the form of for example a preprint?

Thank you!

Pedro

**Comment by giovanniquinones** [comment]
Hi Pedro, 
That method was published around the same time we submitted our paper for peer review. Also, it seems it only finds SNPs, while we wanted to benchmark against methods that call SNPs + INDELs. 
Yes, I think adapting the software for 10X data is a great suggestion and something we are looking into for future versions. 
best,

**Comment by BiotechPedro** [comment]
Thank you for the details, Giovanni!! Here you have one user that will try your method on 10X data if you adapt it 😄 

Cheers,

Pedro
